name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Timeroo
    runs-on: macos-latest

    steps:
      - uses: mxcl/xcodebuild@v3
