name: Xcode - Build and Analyze

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: Build Timeroo
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: |
          xcodebuild clean build analyze -project Timeroo-15.xcodeproj -scheme "Timeroo" | xcpretty && exit ${PIPESTATUS[0]}
#      - uses: mxcl/xcodebuild@v3
#        with:
#          scheme: Timeroo
